spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.40.253:1521/SJK
    username: NTMG
    password: NTMGPASS
    driver-class-name: oracle.jdbc.OracleDriver
server:
  port: 6879
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
