server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      min-spare: 30
      max: 1000
  compression:
    enabled: on
    min-response-size: 1024
    mime-types:
      - text/javascript
      - application/javascript
      - image/png
      - image/jpeg
      - text/html
      - application/json
      - text/css
      - image/gif
      - application/octet-stream
  servlet:
    session:
      timeout: 1800000
    encoding:
      charset: utf-8
      force: on
spring:
  profiles:
    active: test
  jackson:
    default-property-inclusion: ALWAYS
    time-zone: GMT+9
    date-format: yyyy/MM/dd HH:mm:ss Z
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: on
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: on
  mvc:
    throw-exception-if-no-handler-found: on
  datasource:
    hikari:
      poolName: web-work-pool
      # 自动提交从池中返回的连接
      auto-commit: on
      # 连接最大等待毫秒数
      connectionTimeout: 30000
      # 池中连接最长生命周期(1800000ms=30m)
      maxLifetime: 1800000
      # 600000ms 连接池中允许连接闲置的最长时间（如果idleTimeout+1秒>maxLifetime 且 maxLifetime>0，则会被重置为0（代表永远不会退出）；如果idleTimeout!=0且小于10秒，则会被重置为10秒）
      idle-timeout: 600000
      connection-test-query: SELECT 1 FROM DUAL
mybatis-plus:
  mapper-locations: classpath*:jp/smartcompany/job/modules/core/mapper/*Mapper.xml
  type-enums-package: jp.smartcompany.job.modules.*.pojo.enums
  global-config:
    db-config:
      id-type: INPUT
      logic-delete-value: -1
      logic-not-delete-value: 0
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_null
    banner: false
  configuration:
    jdbc-type-for-null: NULL
management:
  endpoints:
    web:
      exposure:
        include: metrics,info,health
  endpoint:
    health:
      show-details: always
security:
  # 不需要拦截的url
  whiteList:
    - /actuator/**
    - /login
    - /logout
    - /sqltest
  # 无需进行登录后授权只需要登录即可的url
  onlyAuthenticationList:
    - /
  # 需要忽略的静态资源url
  resourceList:
    - /favicon.ico
    - /static/**
  # 退出成功后的转向url
  logoutSuccessUrl: /login
  # 登录成功后的转向url
  loginSuccessUrl: /home
  # 登陆失败后的转向url
  loginFailureUrl: /login
  # 授权失败的转向url
  accessDeniedUrl: /403