server:
  servlet:
    session:
      timeout: 600s
  port: 6879
spring:
#  datasource:
#    url: jdbc:oracle:thin:@47.74.25.28:1521/orcl
#    username: SPWM
#    password: SPWMPASS
#    driver-class-name: oracle.jdbc.OracleDriver
#  datasource:
#    url: jdbc:oracle:thin:@192.168.70.42:1521/SJK
#    username: SPWMTEST
#    password: SPWMPASS
#    driver-class-name: oracle.jdbc.OracleDriver
#
  datasource:
    url: jdbc:oracle:thin:@192.168.21.217:1521/TMG
    username: SPWM
    password: SPWMPASS
    driver-class-name: oracle.jdbc.OracleDriver
#  datasource:
#    url: jdbc:oracle:thin:@192.168.21.217:1521/TMG
#    username: SPWMDEV
#    password: SPWMPASS
#    driver-class-name: oracle.jdbc.OracleDriver
#  datasource:
#    url: jdbc:oracle:thin:@192.168.20.160:1521/TMG
#    username: SPWM
#    password: SPWMPASS
#    driver-class-name: oracle.jdbc.OracleDriver
#  datasource:
#    url: jdbc:oracle:thin:@192.168.20.160:1521/TMG
#    username: SPWMTEST
#    password: SPWMPASS
#    driver-class-name: oracle.jdbc.OracleDriver
#  datasource:
#    url: jdbc:oracle:thin:@192.168.20.160:1521/TMG
#    username: SPWMDEV
#    password: SPWMPASS
#    driver-class-name: oracle.jdbc.OracleDriver
mybatis-plus:
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
security:
  ssl: off