server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      min-spare: 30
      max: 1000
  compression:
    enabled: on
    min-response-size: 1024
    mime-types:
      - text/javascript
      - application/javascript
      - image/png
      - image/jpeg
      - text/html
      - application/json
      - text/css
      - image/gif
      - application/octet-stream
  servlet:
    encoding:
      charset: utf-8
      force: on
spring:
  profiles:
    active: prod
  application:
    name: SmartPublic-WM
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: on
  mvc:
    throw-exception-if-no-handler-found: on
  datasource:
    hikari:
      pool-name: web-work-pool
      auto-commit: on
      connection-timeout: 60000
      max-lifetime: 1800000
      idle-timeout: 600000
      connection-test-query: SELECT 1 FROM DUAL
      validation-timeout: 3000
mybatis-plus:
  mapper-locations: classpath:jp/smartcompany/job/modules/core/mapper/**/*.xml,classpath:jp/smartcompany/job/modules/tmg_setting/genericmanager/mapper/**/*.xml
  global-config:
    db-config:
      id-type: INPUT
      logic-delete-value: -1
      logic-not-delete-value: 0
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_null
    banner: false
  configuration:
    jdbc-type-for-null: NULL
  type-enums-package: jp.smartcompany.job.modules.*.enums
management:
  endpoints:
    web:
      exposure:
        include: metrics,info,health
  endpoint:
    health:
      show-details: always
info:
  basePath: /
security:
  csrfWhiteList:
    - /login
    - /logout
    - /McSrvs01
    - /McSrvs01
    - /McSrvs02
    - /McSrvs03
    - /McSrvs04
    - /McSrvs05
    - /McSrvs06
    - /McSrvs07
    - /McSrvs08
  # 不需要拦截的url
  whiteList:
    - /403
    - /404
    - /500
    - /actuator/**
    - /login
    - /logout
    - /McSrvs01
    - /McSrvs02
    - /McSrvs03
    - /McSrvs04
    - /McSrvs05
    - /McSrvs06
    - /McSrvs07
    - /McSrvs08
    - /stamping
  # 无需进行登录后授权只需要登录即可的url
  onlyAuthenticationList:
    - ${info.basePath}
    - ${info.basePath}index
    - ${info.basePath}sys/**
    - ${info.basePath}tmg_admin/**
    - ${info.basePath}tmg_inp/**
    - ${info.basePath}admin/**
    - ${info.basePath}tmg_setting/**
    - ${info.basePath}expirePassword
    - ${info.basePath}changeExpirePassword
    - ${info.basePath}changePassword
  # 需要忽略的静态资源url
  resourceList:
    - /favicon.ico
    - /static/**
  # 退出成功后的转向url
  logoutSuccessUrl: /login
  # 登录成功后的转向url
  loginSuccessUrl: /
  # 登陆失败后的转向url
  loginFailureUrl: /login
  # 授权失败的转向url
  accessDeniedUrl: /403