spring:
  thymeleaf:
    cache: off
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:nsg
    username: tmg_iyaku2
    password: tmg_iyakupass
    driver-class-name: oracle.jdbc.OracleDriver
logging:
  level:
    jp.smartcompany.job.modules.core.service: debug
    jp.smartcompany.job.modules.core.mapper: debug