spring:
#  datasource:
#    url: jdbc:oracle:thin:@47.74.25.28:1521/orcl
#    username: SPWM
#    password: SPWMPASS
#    driver-class-name: oracle.jdbc.OracleDriver
  datasource:
    url: jdbc:oracle:thin:@192.168.20.160:1521/TMG
    username: SPWM
    password: SPWMPASS
    driver-class-name: oracle.jdbc.OracleDriver
#  datasource:
#    url: jdbc:oracle:thin:@192.168.20.160:1521/TMG
#    username: SPWMDEV
#    password: SPWMPASS
#    driver-class-name: oracle.jdbc.OracleDriver
server:
  port: 6879
mybatis-plus:
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl