spring:
  session:
    # session过期时间默认为600秒，即10分钟,小于60秒会被当作60秒处理
    timeout: 600
#  datasource:
#    url: jdbc:oracle:thin:@47.74.25.28:1521/orcl
#    username: SPWM
#    password: SPWMPASS
#    driver-class-name: oracle.jdbc.OracleDriver
#  datasource:
#    url: jdbc:oracle:thin:@192.168.70.42:1521/SJK
#    username: SPWMTEST
#    password: SPWMPASS
#    driver-class-name: oracle.jdbc.OracleDriver
#
  datasource:
    url: jdbc:oracle:thin:@192.168.21.217:1521/TMG
    username: SPWM
    password: SPWMPASS
    driver-class-name: oracle.jdbc.OracleDriver
#  datasource:
#    url: jdbc:oracle:thin:@192.168.20.160:1521/TMG
#    username: SPWM
#    password: SPWMPASS
#    driver-class-name: oracle.jdbc.OracleDriver
#  datasource:
#    url: jdbc:oracle:thin:@192.168.20.160:1521/TMG
#    username: SPWMTEST
#    password: SPWMPASS
#    driver-class-name: oracle.jdbc.OracleDriver
#  datasource:
#    url: jdbc:oracle:thin:@192.168.20.160:1521/TMG
#    username: SPWMDEV
#    password: SPWMPASS
#    driver-class-name: oracle.jdbc.OracleDriver
server:
  port: 6879
mybatis-plus:
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
security:
  ssl: off