spring:
  datasource:
    url: jdbc:oracle:thin:@47.74.25.28:1521/orcl
    username: tmg_iyaku2
    password: tmg_iyakupass
    driver-class-name: oracle.jdbc.OracleDriver
#  datasource:
#    url: jdbc:oracle:thin:@192.168.40.253:1521/SJK
#    username: NTMG
#    password: NTMGPASS
#    driver-class-name: oracle.jdbc.OracleDriver
logging:
  level:
    jp.smartcompany.job.modules.core.service: debug
    jp.smartcompany.job.modules.core.mapper: debug
    jp.smartcompany.job.modules.tmg: debug
server:
  port: 6879
