spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.21.217:1521/TMG
    username: SPWM
    password: SPWMPASS
    driver-class-name: oracle.jdbc.OracleDriver
#  datasource:
#    url: jdbc:oracle:thin:@47.74.25.28:1521/orcl
#    username: SPWM
#    password: SPWMPASS
#    driver-class-name: oracle.jdbc.OracleDriver
  ssl: on
info:
  basePath: /spwm/
  siteUrl: http://localhost:6879/spwm