spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.21.217:1521/TMG
    username: SPWMDEV
    password: SPWMPASS
    driver-class-name: oracle.jdbc.OracleDriver
#  datasource:
#    url: jdbc:oracle:thin:@47.74.25.28:1521/orcl
#    username: SPWM
#    password: SPWMPASS
#    driver-class-name: oracle.jdbc.OracleDriver
security:
  # 无需进行登录后授权只需要登录即可的url
  onlyAuthenticationList:
    - ${info.basePath}
    - ${info.basePath}index
    - ${info.basePath}sys/**
    - ${info.basePath}tmg_admin/**
    - ${info.basePath}tmg_inp/**
    - ${info.basePath}admin/**
    - ${info.basePath}tmg_setting/**
    - ${info.basePath}expirePassword
    - ${info.basePath}changeExpirePassword
    - ${info.basePath}changePassword
  ssl: on
info:
  basePath: /spwm/