spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.21.217:1521/TMG
    username: SPWM
    password: SPWMPASS
    driver-class-name: oracle.jdbc.OracleDriver
#  datasource:
#    url: jdbc:oracle:thin:@47.74.25.28:1521/orcl
#    username: SPWM
#    password: SPWMPASS
#    driver-class-name: oracle.jdbc.OracleDriver
security:
  # 无需进行登录后授权只需要登录即可的url
  onlyAuthenticationList:
    - /web-work/
    - /web-work/index
    - /web-work/sys/**
    - /web-work/tmg_admin/**
    - /web-work/tmg_inp/**
    - /web-work/admin/**
    - /web-work/tmg_settings/**
    - /web-work/expirePassword
    - /web-work/changeExpirePassword
    - /web-work/changePassword
  ssl: on